[tool.poetry]
name = "denser-retriever"
version = "0.1.0"
description = ""
packages = [{ include = "denser_retriever" }]

[tool.poetry.group.test.dependencies]
pytest = "^7.0"


[tool.poetry.group.dev.dependencies]
pytrec-eval = "^0.5"
langchain-text-splitters = "^0.3.6"
openai = "^1.62.0"

[tool.poetry.dependencies]
python = ">=3.10.0,<3.12.0"
torch = [
    { markers = "sys_platform == 'darwin'", url = "https://download.pytorch.org/whl/cpu/torch-2.3.1-cp310-none-macosx_11_0_arm64.whl" },
    { markers = "sys_platform == 'linux'", url = "https://download.pytorch.org/whl/cu121/torch-2.3.1%2Bcu121-cp310-cp310-linux_x86_64.whl" },
    { markers = "sys_platform == 'win32'", url = "https://download.pytorch.org/whl/cu121/torch-2.3.1%2Bcu121-cp310-cp310-win_amd64.whl" },
]
numpy = "^1.26.4"
pymilvus = "^2.5.4"
langchain-core = "^0.3.34"
elasticsearch = "^8.17.1"
sentence-transformers = "^3.4.1"
flagembedding = "^1.3.4"
cohere = "^5.13.12"
chromadb = "^0.6.3"
einops = "^0.8.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
